<<<<<<< HEAD
title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
=======
>>>>>>> 3167d22fec10a528f1acfe7273a3b7a6c817bf9e
